#!/bin/bash -eu

export KDF_INSTALLER=1
. $(dirname $0)/index.bash

function _dotfiles-install {

	echo "$(tput smul)$(tput bold)Home directory...$(tput sgr0)"
	echo

	local src="$HOME/.krinkle.dotfiles"

	# Live links
	_dotfiles-ensure-link "$HOME/.ackrc" "$src/hosts/primary/ackrc"

	# These are copied instead of symlinked to allow local modification,
	# without affecting the Git repository status.
	_dotfiles-ensure-copy "$src/hosts/primary/bashrc" "$HOME/.bashrc"
	_dotfiles-ensure-copy "$src/hosts/primary/bash_profile" "$HOME/.bash_profile"
	_dotfiles-ensure-copy "$src/hosts/primary/bash_sessions_disable" "$HOME/.bash_sessions_disable"

	echo "$(tput setaf 2)>>$(tput sgr0) Home directory ready"

	# Homebrew
	echo "... check Homebrew"
	if [ -z "$(which brew)" ]
	then
		echo "$CLR_RED>> ERROR$CLR_NONE: Install Homebrew first"
		open https://brew.sh
		exit 1
	fi

	echo "... update Homebrew"
	brew update
	echo "... exec 'brew doctor'"
	brew doctor || _dotfiles-prompt-choice "Check out those warnings. Continue?"

	echo "... ensure Homebrew packages"
	formulas=(
		ack
		aspell
		autojump
		bash
		bash-completion@2
		# For 0ad development
		cmake
		colordiff
		composer
		coreutils
		difftastic
		curl
		git
		git-review
		hstr
		jq
		node
		# Needed for php-apcu
		pcre2
		pwgen
		watch
		wget
	)
	for f in "${formulas[@]}"; do
		brew upgrade $f || brew install $f
	done
	brew upgrade php@8.3 || brew install php@8.3

	brew cleanup

	echo "... post-install: bash"
	if ! grep -q /opt/homebrew/bin/bash /etc/shells
	then
		sudo sh -c 'echo "/opt/homebrew/bin/bash" >> /etc/shells'
		chsh -s /opt/homebrew/bin/bash
	fi

	echo "... post-install: php"
	test -f /opt/homebrew/etc/php/8.3/conf.d/krinkle.ini || ( echo "linking php.ini" && ln -s $KDF_BASE_DIR/hosts/primary/php.ini /opt/homebrew/etc/php/8.3/conf.d/krinkle.ini )

	# Fix missing pcre2 dep for php-apcu.
	#
	# https://stackoverflow.com/a/72612925/319266
	# https://github.com/Homebrew/homebrew-core/issues/102392
	#
	# > /opt/homebrew/Cellar/php/8.x.x/include/php/ext/pcre/php_pcre.h:23:10:
	# > fatal error: 'pcre2.h' file not found
	#
	# This worked fine on macOS 10.15, but on macOS 13+, pcre2 is either no longer
	# installed by default, or (if it is) it's not linked properly?
	ln -s /opt/homebrew/opt/pcre2/include/pcre2.h /opt/homebrew/opt/php@8.3/include/php/ext/pcre/
	pecl install apcu ast excimer pcov

	echo "... post-install: git"
	_dotfiles-ensure-link ~/.gitconfig "$KDF_BASE_DIR/hosts/primary/gitconfig"

	echo "... post-install: ssh"
	_dotfiles-ensure-link ~/.ssh/config "$KDF_BASE_DIR/hosts/primary/sshconfig"

	echo "... check Sublime Text"
	if [ -z "$(which subl)" ]
	then
		echo "$CLR_RED>> ERROR$CLR_NONE: Install Sublime Text and re-run the installer."
		open http://www.sublimetext.com/download
		exit 1
	fi

	echo "... post-install: Sublime Text"
	tmpPath="$HOME/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"
	tmpDest=$KDF_BASE_DIR/hosts/primary/SublimePreferences.json
	_dotfiles-ensure-link "$tmpPath" "$tmpDest"

	tmpPath=$HOME/.config
	tmpDest=$KDF_BASE_DIR/hosts/primary/config
	_dotfiles-ensure-link "$tmpPath" "$tmpDest"
}

_dotfiles-install

echo
echo "$(tput setaf 2)>>$(tput sgr0) Installation complete"

# Re-source after install
. $(dirname $0)/index.bash
